import telebot
from telebot import types

btn1 = types.KeyboardButton('📲 Зарегистрироваться')
btn2 = types.KeyboardButton('📋 Мои данные')
btn3 = types.KeyboardButton('👀 Мероприятия')
btn4 = types.KeyboardButton('➕ Добавить ивент')
btn5 = types.KeyboardButton('👉 Выбрать ивент')
btn7 = types.KeyboardButton('👀 Все пользователи')
btn8 = types.KeyboardButton('📄 Файл')
btn9 = types.KeyboardButton('1. ФИО')
btn10 = types.KeyboardButton('2. Вуз')
btn11 = types.KeyboardButton('3. Курс')
btn12 = types.KeyboardButton('4. Институт (факультет)')
btn13 = types.KeyboardButton('⬅️ Назад')
btn14 = types.KeyboardButton('✏️ Изменить данные')
btn15 = types.KeyboardButton('📃 О клубе')
btn16 = types.KeyboardButton('🅾️ Изменить текст') 
btn17 = types.KeyboardButton('🅾️ Изменить фото')
btn18 = types.KeyboardButton('✅ Да')
btn19 = types.KeyboardButton('📤 Отправить рассылку')
btn20 = types.KeyboardButton('⬅️ В меню')
btn21 = types.KeyboardButton('👨‍👨‍👦 Участники')
btn22 = types.KeyboardButton('✍️ Изменить')
btn23 = types.KeyboardButton('❌ Удалить')